### ISSUE TITLE
Using your code for text file

### ISSUE THREAD

**Issue by AmirTarighat** [cherry247/chatbot-using-python#1]
Hi Shaili,

I watched your interesting video on youtube creating attractive chatbot. I'd like to use this part of your code as follows for an existing text file on my computer. I mean I DO NOT want to download anything with an url from web. Instead of web I need to use a text file. Please help me how to do so.

Thanks a lot!
==============================
      #get artical url
      article= Article('https://simple.wikipedia.org/wiki/Light')
      article.download()
      article.parse()
      article.nlp()
      corpus=article.text
      print(corpus)
=================================

**Comment by cherry247** [comment]
Hey Amir,
Glad to help you out.
we can use nltk as it helps in  accessing text from the Web and from Disk.

`import nltk.data
corpus=nltk.data.load('...../filename.txt')
`
nltk.data.load('your file path')
I hope this helps you.

**Comment by AmirTarighat** [comment]
Hi Shaili,

Thank you so much for your help. With some changes in code I got the expected results. You did a great job!

Good luck
